### ISSUE TITLE
How to get my backend address?

### ISSUE THREAD

**Issue by YIRU69** [SimeonLukas/Obsidian2Kindle#1]
Firstly，Thanks for you share!
And now I try to use it but have some problem.
How to get my backend address?
try to search in internet

**Comment by SimeonLukas** [comment]
Hi YIRU69,

Do you have PHP running on your Server or PC?
When you host local, do the following:

$ cd ~/ob2ki-directory // go to the directory where you saved the files and index.php is located and open the terminal.
$ php -S localhost:8000 // run this command! now your local backendadress is http://localhost:8000.

Don't forget to install the gd lib.

Greetings,
Simeon

**Comment by YIRU69** [comment]
yeah, I complete install PHP and Apache24, and also install the gd lib
And now I don't konw how to do next. 0.0
1. I haven't ~/ob2ki-directory , Can I create file folder?
2. How can  I create "index.php"

Thanks to help me a lot!

**Comment by SimeonLukas** [comment]
Just download the files from the repo.
In the root folder is the index.php file.
Put all the files from the repo in one folder, and than start the command.
I hope this helps.

Thanks for your patience.
Greetings!

**Comment by YIRU69** [comment]
Look it many error...
```

Warning: Undefined array key "HTTP_ORIGIN" in D:\PHP\Obsidian2Kindle\index.php on line 11

Deprecated: Optional parameter $verb declared before required parameter $ip is implicitly treated as a required parameter in D:\PHP\Obsidian2Kindle\MOBIClass\Http.php on line 16

Warning: Undefined array key "text" in D:\PHP\Obsidian2Kindle\index.php on line 28

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in D:\PHP\Obsidian2Kindle\parsedown.php on line 43

Warning: Undefined array key "Bilder" in D:\PHP\Obsidian2Kindle\index.php on line 36

Warning: Undefined array key "toc" in D:\PHP\Obsidian2Kindle\index.php on line 66

Warning: Undefined array key "title" in D:\PHP\Obsidian2Kindle\index.php on line 77

Warning: Undefined array key "author" in D:\PHP\Obsidian2Kindle\index.php on line 78

Warning: Undefined array key "author" in D:\PHP\Obsidian2Kindle\index.php on line 79

Warning: Undefined array key "title" in D:\PHP\Obsidian2Kindle\index.php on line 87

Deprecated: imagettftext(): Passing null to parameter #8 ($text) of type string is deprecated in D:\PHP\Obsidian2Kindle\index.php on line 87

Warning: Undefined array key "author" in D:\PHP\Obsidian2Kindle\index.php on line 88

Deprecated: imagettftext(): Passing null to parameter #8 ($text) of type string is deprecated in D:\PHP\Obsidian2Kindle\index.php on line 88

Warning: Undefined array key "toc" in D:\PHP\Obsidian2Kindle\index.php on line 93

Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in D:\PHP\Obsidian2Kindle\MOBIClass\MOBIFile.php on line 34

Warning: Undefined array key "title" in D:\PHP\Obsidian2Kindle\index.php on line 132

Fatal error: Uncaught Error: Call to undefined function mb_str_split() in D:\PHP\Obsidian2Kindle\MOBIClass\RecordFactory.php:41 Stack trace: #0 D:\PHP\Obsidian2Kindle\MOBIClass\MOBI.php(162): RecordFactory->createRecords('<html lang='de'...') #1 D:\PHP\Obsidian2Kindle\MOBIClass\MOBI.php(182): MOBI->preparePRC() #2 D:\PHP\Obsidian2Kindle\index.php(132): MOBI->save('.mobi') #3 {main} thrown in D:\PHP\Obsidian2Kindle\MOBIClass\RecordFactory.php on line 41
```
and try to run plugin
![Snipaste_2022-03-14_18-41-37](https://user-images.githubusercontent.com/48148292/158156800-5aaabb2c-5c7b-49fa-a5d7-a430798f37b2.png)

I have a little software experience , maybe I should give up...
And I should to say 
Thank you very much! Nice to you reply

**Comment by SimeonLukas** [comment]
I'm sorry for this!
On my Server it works without these issues.
So it didn't sent the file to the Kindle?

Greetings,
Simeon

**Comment by YIRU69** [comment]
@SimeonLukas Hi friend, I work it on my windows computer!
It have some important things should to notice.
In the php `php.ini` file, I should open some value.
	1. extension=openssl
	2. extension=mbstring
	3. extension=mysqli
	4. extension=gd
At the end, thank you very much! Keep going!

**Comment by SimeonLukas** [comment]
Hi YIRU69,

Oh thanks for your Info!
I'm going to add this to the readme.

Greetings,
Simerl
