### ISSUE TITLE
Export Error: Call to undefined method TPEpubCreator::error()  -- missing function.

### ISSUE THREAD

**Issue by evitiello** [SimeonLukas/Obsidian2Kindle#2]
Hi - I just installed the server and I get the following error when attempting the export in obsidian.

After digging into the code, the source of the problem was I didn't have the php zip extension installed, however it looks like it uncovered the fact that it's trying to call the error() function in TPEpubCreator.php, and that function doesn't exist.

```
<br />
<b>Fatal error</b>: Uncaught Error:
Call to undefined method
TPEpubCreator::error() in /home/[REDACTED]/TPEpubCreator.php
676
Stack trace:
#0 /home/[REDACTED]/TPEpubCreator.php
(483): TPEpubCreator-&gt;CreateZip()
#1 /home/[REDACTED]/index.php(135):
TPEpubCreator-&gt;CreateEPUB( #2 {main} thrown in <b>/home/[REDACTED]/TPEpubCreator.ohp
<lb> on line <b>676</b><br />
```

**Comment by SimeonLukas** [comment]
Hi evitiello,

I'm really sorry for this problem.
Which php Version do you have?

Greetings,
Simeon

**Comment by SimeonLukas** [comment]
I was able to recreate the problem.
It is the php-zip Extension.
Did you install the right extension for your php Version?

Like:
```
sudo apt install php8.1-zip
```

And do www-data have write permission to the folder?


Greetings,
Simeon 

![IMG_20220906_110048.jpg](https://user-images.githubusercontent.com/33984591/188593634-b38f2ba7-8480-4d31-89d7-31da641cf169.jpg)

**Comment by evitiello** [comment]
Hi - yes I resolved the root cause of missing the zip package - that's all fixed.  But that issue uncovered that TPEpubCreator.php is missing an error() function that it was trying to call, so no error was printed to the log.

**Comment by SimeonLukas** [comment]
Ahhh now I understand.
Thank you very much.

I'm going to fix this.

Greetings,
Simeon

**Comment by SimeonLukas** [comment]
Now I added an extension Check at the Beginning of the Script.
I think this works fine.
Greetings and thanks,
Simeon
