### ISSUE TITLE
Problems with the basic stuff

### ISSUE THREAD

**Issue by FTechTitan** [SimeonLukas/Obsidian2Kindle#3]
Hi SimeonLukas, first thank you for the plugin is a great idea

Second, I tried adding the SMTP host, domain, user and password, and nothing happens

Using default backend

Any idea about what could be wrong? Just used gmail cloud api, and creates oauth credentials...

**Comment by luisher98** [comment]
Hello, im having the same issue as @peacefulwebwarrior . The difference is that im not using gmail cloud api but one and one but the issue i'm having can be related. I tried both hosting the backend locally as well as using the default backend.

**Comment by SimeonLukas** [comment]
Hithere and I'm sorry you have Problems with my Backend..
It is kind of complicated to reproduce the issue.

Do you have the onetime-app-password from Google?

Did you try Port 465?

Greetings
Simeon
